import { db } from '@/db';
import { posts } from '@/db/schema';

async function main() {
    const samplePosts = [
        {
            userId: 3,
            title: 'Looking for React Developer for SaaS Project',
            description: 'Building a modern SaaS platform for team collaboration. Need an experienced React developer who is familiar with TypeScript, Next.js, and state management. The project is in early stages and we are looking for a long-term collaborator. Equity options available for the right candidate.',
            type: 'collab',
            tags: JSON.stringify(['frontend', 'react', 'saas', 'typescript']),
            status: 'open',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 7,
            title: 'Building an AI-Powered Content Generator',
            description: 'Currently developing an AI-powered content generation tool using GPT-4 and custom fine-tuned models. Looking for feedback and potential collaborators interested in NLP and machine learning. Already have a working prototype with 500+ beta users.',
            type: 'project',
            tags: JSON.stringify(['ai', 'backend', 'python', 'nlp']),
            status: 'in_progress',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 2,
            title: 'Best practices for API design?',
            description: 'What are your thoughts on REST vs GraphQL in 2024? I am designing an API for a large-scale application and would love to hear about your experiences with different approaches, versioning strategies, and authentication patterns.',
            type: 'discussion',
            tags: JSON.stringify(['backend', 'api', 'architecture']),
            status: 'open',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 5,
            title: 'Need UI/UX Designer for Mobile App',
            description: 'Seeking a talented UI/UX designer for a health and wellness mobile app. Need someone who can create modern, intuitive designs with a focus on accessibility and user engagement. Project duration: 2-3 months. Paid opportunity with potential for ongoing work.',
            type: 'collab',
            tags: JSON.stringify(['design', 'mobile', 'ui/ux']),
            status: 'open',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            userId: 1,
            title: 'Completed: E-commerce Platform with Next.js',
            description: 'Successfully launched a full-featured e-commerce platform built with Next.js, Stripe payments, and PostgreSQL. Features include real-time inventory management, order tracking, and admin dashboard. Open to sharing insights and codebase with the community.',
            type: 'project',
            tags: JSON.stringify(['frontend', 'nextjs', 'fullstack']),
            status: 'closed',
            createdAt: new Date('2023-12-10').toISOString(),
            updatedAt: new Date('2023-12-10').toISOString(),
        },
        {
            userId: 9,
            title: 'Seeking Backend Developer for Web3 Startup',
            description: 'Early-stage Web3 startup building a decentralized marketplace. Need a backend developer experienced with Solidity, Ethereum, and Node.js. Must be passionate about blockchain technology and decentralized systems. Competitive salary + tokens.',
            type: 'collab',
            tags: JSON.stringify(['backend', 'web3', 'blockchain']),
            status: 'in_progress',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 4,
            title: 'How to scale Node.js applications?',
            description: 'My Node.js application is starting to hit performance bottlenecks at around 10k concurrent users. Looking for advice on horizontal scaling, load balancing, and caching strategies. What tools and patterns have worked best for you?',
            type: 'discussion',
            tags: JSON.stringify(['backend', 'nodejs', 'devops']),
            status: 'open',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            userId: 6,
            title: 'Building a Task Management Tool',
            description: 'Creating a next-generation task management and productivity tool with AI-powered prioritization and smart scheduling. Tech stack: React, Node.js, MongoDB. Looking for beta testers and potential co-founders interested in the productivity space.',
            type: 'project',
            tags: JSON.stringify(['fullstack', 'saas', 'productivity']),
            status: 'in_progress',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            userId: 8,
            title: 'Looking for Marketing Co-founder',
            description: 'Technical co-founder seeking a marketing-savvy partner for a B2B SaaS product. Product is built and has initial traction with 50 paying customers. Need someone who can drive growth, handle customer acquisition, and develop go-to-market strategy.',
            type: 'collab',
            tags: JSON.stringify(['marketing', 'startup', 'saas']),
            status: 'open',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            userId: 10,
            title: 'Thoughts on microservices architecture?',
            description: 'We migrated from monolith to microservices last year. While it solved some problems, it created others. What has been your experience? When is it worth the complexity and when should you stick with a monolith?',
            type: 'discussion',
            tags: JSON.stringify(['backend', 'architecture', 'devops']),
            status: 'closed',
            createdAt: new Date('2023-12-20').toISOString(),
            updatedAt: new Date('2023-12-20').toISOString(),
        },
        {
            userId: 3,
            title: 'Developing a Health & Fitness App',
            description: 'Building a comprehensive health and fitness tracking application with workout plans, nutrition tracking, and progress analytics. Looking for developers interested in health tech to join the team. React Native, Firebase, and TensorFlow for ML features.',
            type: 'project',
            tags: JSON.stringify(['mobile', 'health', 'frontend']),
            status: 'open',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            userId: 7,
            title: 'Need Python Developer for Data Analytics Tool',
            description: 'Seeking an experienced Python developer to help build a data analytics and visualization platform. Should have expertise in pandas, NumPy, and data visualization libraries. Project involves processing large datasets and creating interactive dashboards. 3-month contract with possibility of extension.',
            type: 'collab',
            tags: JSON.stringify(['backend', 'python', 'data']),
            status: 'in_progress',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            userId: 2,
            title: 'Launched: Open Source Design System',
            description: 'Just released our comprehensive design system as an open source project! Includes 50+ components, dark mode support, accessibility features, and extensive documentation. Built with React and TypeScript. Check it out on GitHub and contributions are welcome!',
            type: 'project',
            tags: JSON.stringify(['design', 'opensource', 'ui', 'react']),
            status: 'closed',
            createdAt: new Date('2023-12-15').toISOString(),
            updatedAt: new Date('2023-12-15').toISOString(),
        },
        {
            userId: 5,
            title: 'Collaborating on AI Chat Assistant',
            description: 'Building an intelligent chat assistant that can integrate with multiple platforms (Slack, Discord, Teams). Using OpenAI API and custom training data. Looking for developers interested in AI and conversational interfaces to join the project.',
            type: 'collab',
            tags: JSON.stringify(['ai', 'nlp', 'backend']),
            status: 'open',
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            userId: 9,
            title: 'What\'s your favorite state management library?',
            description: 'Redux, Zustand, Jotai, Recoil, or Context API? With so many options available, what do you prefer for React state management in 2024? Share your experiences and reasoning. Particularly interested in performance considerations for large applications.',
            type: 'discussion',
            tags: JSON.stringify(['frontend', 'react', 'javascript']),
            status: 'open',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
    ];

    await db.insert(posts).values(samplePosts);
    
    console.log('✅ Posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});