import { db } from '@/db';
import { users } from '@/db/schema';
import bcrypt from 'bcrypt';

async function main() {
    const hashedPassword = await bcrypt.hash("password123", 10);
    
    const sampleUsers = [
        {
            name: 'Alex Chen',
            email: 'alex.chen@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
            bio: 'Full-stack developer passionate about building scalable web applications. Love working with modern JavaScript frameworks.',
            skills: JSON.stringify(['React', 'Node.js', 'TypeScript']),
            xp: 2500,
            badges: JSON.stringify(['Early Adopter', 'Collaborator']),
            role: 'user',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Sarah Miller',
            email: 'sarah.miller@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
            bio: 'UI/UX Designer focused on creating intuitive and beautiful user experiences. Figma enthusiast.',
            skills: JSON.stringify(['Design', 'UI/UX', 'Figma']),
            xp: 3200,
            badges: JSON.stringify(['Top Contributor']),
            role: 'user',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Marcus Johnson',
            email: 'marcus.johnson@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
            bio: 'Product Manager with a track record of launching successful products. Data-driven decision maker.',
            skills: JSON.stringify(['Product Management', 'Marketing']),
            xp: 1800,
            badges: JSON.stringify(['Mentor']),
            role: 'user',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Emily Wong',
            email: 'emily.wong@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
            bio: 'Frontend developer specializing in React and TypeScript. Always learning new technologies.',
            skills: JSON.stringify(['React', 'TypeScript', 'UI/UX']),
            xp: 2100,
            badges: JSON.stringify([]),
            role: 'user',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'David Kumar',
            email: 'david.kumar@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
            bio: 'Backend engineer building robust APIs and microservices. Python and Node.js specialist.',
            skills: JSON.stringify(['Node.js', 'Python', 'DevOps']),
            xp: 3500,
            badges: JSON.stringify(['Early Adopter', 'Top Contributor']),
            role: 'user',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Lisa Park',
            email: 'lisa.park@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
            bio: 'Marketing specialist helping tech companies tell their story. Content creator and strategist.',
            skills: JSON.stringify(['Marketing', 'Product Management']),
            xp: 1200,
            badges: JSON.stringify(['Collaborator']),
            role: 'user',
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
        {
            name: 'Tom Anderson',
            email: 'tom.anderson@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom',
            bio: 'DevOps engineer automating infrastructure and improving deployment pipelines. Cloud architecture expert.',
            skills: JSON.stringify(['DevOps', 'Python', 'Node.js']),
            xp: 2800,
            badges: JSON.stringify([]),
            role: 'user',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Rachel Green',
            email: 'rachel.green@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
            bio: 'Data Scientist turning complex data into actionable insights. Machine learning and analytics enthusiast.',
            skills: JSON.stringify(['Data Science', 'Python']),
            xp: 1500,
            badges: JSON.stringify(['Mentor']),
            role: 'user',
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        {
            name: 'Chris Lee',
            email: 'chris.lee@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris',
            bio: 'Full-stack developer with expertise in modern web technologies. GraphQL and TypeScript advocate.',
            skills: JSON.stringify(['TypeScript', 'GraphQL', 'React', 'Node.js']),
            xp: 4200,
            badges: JSON.stringify(['Early Adopter', 'Top Contributor', 'Mentor']),
            role: 'user',
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            name: 'Nina Patel',
            email: 'nina.patel@email.com',
            password: hashedPassword,
            avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
            bio: 'Product Designer crafting delightful user experiences. Design systems and accessibility advocate.',
            skills: JSON.stringify(['Design', 'UI/UX', 'Figma']),
            xp: 2900,
            badges: JSON.stringify(['Collaborator', 'Top Contributor']),
            role: 'user',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});